Repository prettytable/prettytable, pull requests merged in 2020-11, with the labels that each got.

#75 Add add_rows to add several rows at once
  README.md
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Added, enhancement

#78 Don't create universal wheel for Python 2 (and 3)
  .github/release-drafter.yml
  .github/workflows/labels.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  setup.cfg
Labels: changelog: Fixed

#79 Stop testing on Travis CI due to new open-source limitations
  .travis.yml
Labels: changelog: Changed, testing

#80 Fix padding_width = 0
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: bug, changelog: Fixed

#81 Add <tbody> and <thead> tags
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Added, enhancement

#84 Docs: Update get_html_string with thead and tbody tags
  README.md
Labels: changelog: Fixed, docs

#83 Support formatting options in get_json_string()
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Added, enhancement
