Repository prettytable/prettytable, pull requests merged in 2020-10, with the labels that each got.

#58 Test on and declare support for Python 3.9
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CHANGELOG.md
  setup.cfg
  setup.py
  tox.ini
Labels: enhancement

#56 Use wcwidth for better wide char support
  CHANGELOG.md
  COPYING
  prettytable.py
  prettytable_test.py
  setup.py
Labels: enhancement

#48 Add get_csv_string.
  prettytable.py
  prettytable_test.py
Labels: enhancement

#59 CI: Only run deploy stage for tags
  .travis.yml
Labels: release

#60 Docs: Update and fix changelog, add release checklist
  CHANGELOG.md
  RELEASING.md
Labels: docs

#61 Update release checklist to deploy from GitHub Actions
  .travis.yml
  RELEASING.md
Labels: docs, release

#63 Use Release Drafter to release GH Releases from labelled PRs
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
Labels: release

#64 Use Release Drafter to draft GH Releases from labelled PRs
  .github/workflows/release-drafter.yml
Labels: changelog: skip, release

#62 Fix string comparison and deprecation warning
  .pre-commit-config.yaml
  README.md
  prettytable.py
  prettytable_test.py
Labels: bug, changelog: Fixed

#66 Add setuptools as a dependency
  setup.py
Labels: changelog: Fixed

#67 Update tests
  .pre-commit-config.yaml
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RELEASING.md
  prettytable_test.py
  tox.ini
Labels: changelog: skip, docs, testing

#68 Drop support for EOL Python 2.7 and 3.5
  .pre-commit-config.yaml
  prettytable.py
  prettytable_test.py
  setup.py
  tox.ini
Labels: changelog: Removed

#69 Move to src/ and tests/ layout
  setup.py
  src/prettytable/__init__.py
  src/prettytable/prettytable.py
  tests/test_prettytable.py
  tox.ini
Labels: changelog: Changed

#71 readme: update function name in example
  README.md
Labels: bug, changelog: Fixed, docs
