Repository prettytable/prettytable, pull requests merged in 2021-06, with the labels that each got.

#106 Add auto index column
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Added, enhancement

#117 Use declarative metadata and support PyPy3
  .github/release-drafter.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  setup.cfg
  setup.py
  tox.ini
Labels: changelog: Added

#115 Access properties instead of protected fields in _get_options()
  src/prettytable/prettytable.py
Labels: changelog: Added

#118 CI: Set permissions for Release Drafter
  .github/workflows/release-drafter.yml
Labels: changelog: skip, testing

#104 Add support for positional junction characters and add "double_border" table style
  README.md
  src/prettytable/__init__.py
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Added, enhancement

#119 Refactor for readability and avoid merge conflicts
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Changed
