Repository prettytable/prettytable, pull requests merged in 2022-10, with the labels that each got.

#205 Added type hints from typeshed
  .pre-commit-config.yaml
  setup.py
  src/prettytable/__init__.py
  src/prettytable/colortable.py
  src/prettytable/prettytable.py
  tests/test_colortable.py
  tests/test_prettytable.py
Labels: changelog: Added, hacktoberfest-accepted

#210 Replace 3.11-dev with 3.11
  .github/workflows/test.yml
Labels: testing, changelog: skip

#211 added py.typed and updated setup.cfg
  setup.cfg
  src/prettytable/py.typed
Labels: changelog: Added

#212 Convert from setuptools to hatchling
  .flake8
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: changelog: Changed
