Repository prettytable/prettytable, pull requests merged in 2024-10, with the labels that each got.

#316 Add attribute type hints
  .pre-commit-config.yaml
  src/prettytable/prettytable.py
Labels: changelog: Added

#318 Add type annotations for attributes property
  src/prettytable/prettytable.py
Labels: changelog: Added

#319 Improve function type annotations
  src/prettytable/prettytable.py
Labels: changelog: Added

#312 Add new themes to `ColorTable`
  src/prettytable/colortable.py
  tests/test_colortable.py
Labels: changelog: Added

#321 Generate `__version__` at build to avoid slow `importlib.metadata` call
  .github/workflows/lint.yml
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  src/prettytable/__init__.py
  src/prettytable/prettytable.py
  tox.ini
Labels: changelog: Changed

#320 Improve TableHandler type annotations
  src/prettytable/prettytable.py
Labels: changelog: Fixed

#322 Improve row and column type annotations
  src/prettytable/prettytable.py
Labels: changelog: Changed

#315 Use SPDX license identifier
  .pre-commit-config.yaml
  pyproject.toml
Labels: changelog: Added

#324 Improve type annotations for field names
  src/prettytable/prettytable.py
Labels: changelog: Changed

#325 Add type aliases for Align, VAlign, HeaderStyle
  src/prettytable/prettytable.py
Labels: changelog: Added

#326 Add IntEnum for Table styles
  src/prettytable/__init__.py
  src/prettytable/prettytable.py
Labels: changelog: Added

#327 Add IntEnum for HRuleStyle and VRuleStyle
  src/prettytable/__init__.py
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Added

#330 Add missing attribute annotations
  src/prettytable/prettytable.py
Labels: changelog: Added

#331 Test with tox-uv
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: changelog: skip

#333 Include RowType in __all__
  src/prettytable/__init__.py
Labels: changelog: Added

#335 Update new home to prettytable/prettytable
  .github/FUNDING.yml
  .github/SECURITY.md
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  RELEASING.md
  pyproject.toml
Labels: changelog: Changed

#334 Add `OptionsType`
  src/prettytable/prettytable.py
Labels: changelog: Added

#336 Release to PyPI using Trusted Publishing
  .github/workflows/release.yml
  RELEASING.md
Labels: changelog: Added

#332 Fix drawing headerless colored tables with title
  src/prettytable/prettytable.py
  tests/test_colortable.py
Labels: changelog: Fixed

#329 Emit DeprecationWarnings for hrule and tableStyle constants
  src/prettytable/__init__.py
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Deprecated

#337 Only emit DeprecationWarning once
  src/prettytable/prettytable.py
Labels: changelog: skip

#339 Use Codecov with a token
  .github/workflows/test.yml
Labels: changelog: skip

#340 PEP 703 attestations are now the default
  .github/workflows/release.yml
Labels: changelog: skip
