Repository prettytable/prettytable, pull requests merged in 2025-02, with the labels that each got.

#358 Add option to truncate column headers to column width
  README.md
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Added

#359 Add `row_filter` option
  README.md
  src/prettytable/prettytable.py
  tests/test_colortable.py
  tests/test_prettytable.py
Labels: changelog: Added

#360 perf: remove unnecessary deepcopies and add some lru_caches
  src/prettytable/prettytable.py
Labels: changelog: Changed

#361 Add option to avoid break on hyphen in longer texts
  README.md
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Added

#363 Refactor tests
  .pre-commit-config.yaml
  tests/conftest.py
  tests/test_colortable.py
  tests/test_html.py
  tests/test_json.py
  tests/test_latex.py
  tests/test_prettytable.py
  tests/test_sections.py
  tests/test_sorting.py
  tests/test_style.py
Labels: changelog: skip

#368 Add MediaWiki table support
  README.md
  src/prettytable/__init__.py
  src/prettytable/prettytable.py
  tests/conftest.py
  tests/test_mediawiki.py
  tests/test_prettytable.py
Labels: changelog: Added

#370 Use `_str_block_width` to calculate title width
  src/prettytable/prettytable.py
  tests/test_style.py
Labels: changelog: Fixed

#369 Create divider with `add_rows()`
  README.md
  src/prettytable/prettytable.py
  tests/test_sections.py
Labels: changelog: Added

#371 Remove unnecessary start=0 from `range`
  pyproject.toml
  src/prettytable/prettytable.py
Labels: changelog: Changed

#372 Defer type-checking and `warnings` imports
  src/prettytable/prettytable.py
  tests/test_colortable.py
Labels: changelog: Changed

#373 Check all test files with mypy
  .coveragerc
  pyproject.toml
  src/prettytable/prettytable.py
  tests/test_colortable.py
  tests/test_latex.py
  tests/test_prettytable.py
  tox.ini
Labels: changelog: skip

#374 Missing types in tests
  tests/conftest.py
  tests/test_colortable.py
  tests/test_json.py
  tests/test_latex.py
  tests/test_prettytable.py
  tests/test_sorting.py
  tests/test_style.py
Labels: changelog: skip

#375 Add support for PyPy3.11
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  README.md
Labels: changelog: Added

#376 Move mypy version to updateable requirements file
  .pre-commit-config.yaml
  requirements-mypy.txt
  tox.ini
Labels: changelog: skip

#378 Fix `IndexError` for `add_rows()` with an empty list
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Fixed

#379 Fix typing: replace `Iterable` with indexable `Sequence`
  src/prettytable/prettytable.py
Labels: changelog: Fixed
