Repository prettytable/prettytable, pull requests merged in 2025-01, with the labels that each got.

#346 Use `TableStyle` in `README.md`
  README.md
Labels: changelog: Fixed

#343 Consider column args when columns are set after initialization (#272)
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Fixed

#345 Fix `add_autoindex` alignment for HTML
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Fixed

#344 Fix default styles not being reset between `set_style()` calls
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Fixed

#348 Update pre-commit
  .github/workflows/labels.yml
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/require-pr-label.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/prettytable/__init__.py
  src/prettytable/prettytable.py
  tox.ini
Labels: changelog: Changed

#349 Add support for Python 3.14
  .github/workflows/test.yml
  pyproject.toml
  tox.ini
Labels: changelog: Added

#347 Add demo to `__main__`: `python -m prettytable`
  .coveragerc
  README.md
  src/prettytable/__main__.py
Labels: changelog: Added

#350 Use PEP 639 licence expression
  pyproject.toml
Labels: changelog: Added

#351 Add missing quote
  src/prettytable/prettytable.py
Labels: changelog: Fixed

#356 Fix divider intersection for border styles
  src/prettytable/prettytable.py
  tests/test_prettytable.py
Labels: changelog: Fixed

#357 Add `add_divider()` method to create sections
  README.md
  src/prettytable/prettytable.py
  tests/test_prettytable.py
  tests/test_sections.py
Labels: changelog: Added
